name: PR_test
on:
  push:
    branches:
      - SW-115/auto-tdd
jobs:
  PR_test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x] # ".x" 로 최신 버전도 사용하고 직접 버전 지정도 가능하다
    steps:
      - name: 풀리퀘 브랜치 헤드로 체크아웃
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: 노드 모듈 캐싱
        uses: actions/cache@v1
        with:
          path: front/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: 노드 모듈 설치
        run: cd front && npm install
